extends Node

@warning_ignore("unused_signal")
signal world_snapshot_updated(width: int, height: int, seed_hash: int)
@warning_ignore("unused_signal")
signal location_changed(location: Dictionary)
@warning_ignore("unused_signal")
signal regional_step_taken(location: Dictionary)
@warning_ignore("unused_signal")
signal battle_started(encounter: Dictionary)
@warning_ignore("unused_signal")
signal battle_resolved(result: Dictionary)
@warning_ignore("unused_signal")
signal poi_entered(poi_data: Dictionary)
@warning_ignore("unused_signal")
signal menu_opened(context_title: String)
@warning_ignore("unused_signal")
signal menu_closed(context_title: String)
@warning_ignore("unused_signal")
signal party_changed(party: Dictionary)
@warning_ignore("unused_signal")
signal inventory_changed(inventory: Dictionary)
@warning_ignore("unused_signal")
signal time_advanced(time_label: String)
@warning_ignore("unused_signal")
signal settings_changed(settings: Dictionary)
@warning_ignore("unused_signal")
signal quests_changed(quests: Dictionary)
@warning_ignore("unused_signal")
signal world_flags_changed(flags: Dictionary)
@warning_ignore("unused_signal")
signal save_written(path: String)
@warning_ignore("unused_signal")
signal save_loaded(path: String)
